# Site settings
title: IFT503 - Operating System
email: nono -- AT -- cs.unsika.ac.id
description: "Unsika course, Operating System"
url: "http://nonohry.github.io/IFT503"
twitter_username: nonohry
github_username:  nonohry


# Build settings
markdown: kramdown
